// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/hierachain.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxStatus_Status int32

const (
	TxStatus_PENDING   TxStatus_Status = 0
	TxStatus_CONFIRMED TxStatus_Status = 1
	TxStatus_FAILED    TxStatus_Status = 2
)

// Enum value maps for TxStatus_Status.
var (
	TxStatus_Status_name = map[int32]string{
		0: "PENDING",
		1: "CONFIRMED",
		2: "FAILED",
	}
	TxStatus_Status_value = map[string]int32{
		"PENDING":   0,
		"CONFIRMED": 1,
		"FAILED":    2,
	}
)

func (x TxStatus_Status) Enum() *TxStatus_Status {
	p := new(TxStatus_Status)
	*p = x
	return p
}

func (x TxStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_hierachain_proto_enumTypes[0].Descriptor()
}

func (TxStatus_Status) Type() protoreflect.EnumType {
	return &file_api_proto_hierachain_proto_enumTypes[0]
}

func (x TxStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxStatus_Status.Descriptor instead.
func (TxStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{4, 0}
}

// Transaction represents a single blockchain transaction.
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ArrowPayload  []byte                 `protobuf:"bytes,4,opt,name=arrow_payload,json=arrowPayload,proto3" json:"arrow_payload,omitempty"` // Arrow IPC serialized payload
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_hierachain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hierachain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Transaction) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Transaction) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Transaction) GetArrowPayload() []byte {
	if x != nil {
		return x.ArrowPayload
	}
	return nil
}

func (x *Transaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Transaction) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// TransactionBatch is a collection of transactions for batch processing.
type TransactionBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBatch) Reset() {
	*x = TransactionBatch{}
	mi := &file_api_proto_hierachain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBatch) ProtoMessage() {}

func (x *TransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hierachain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBatch.ProtoReflect.Descriptor instead.
func (*TransactionBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionBatch) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// BatchResult contains the result of batch transaction processing.
type BatchResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProcessedTxIds   []string               `protobuf:"bytes,3,rep,name=processed_tx_ids,json=processedTxIds,proto3" json:"processed_tx_ids,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,4,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	Errors           []*TxError             `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchResult) Reset() {
	*x = BatchResult{}
	mi := &file_api_proto_hierachain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResult) ProtoMessage() {}

func (x *BatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hierachain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResult.ProtoReflect.Descriptor instead.
func (*BatchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{2}
}

func (x *BatchResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchResult) GetProcessedTxIds() []string {
	if x != nil {
		return x.ProcessedTxIds
	}
	return nil
}

func (x *BatchResult) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *BatchResult) GetErrors() []*TxError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// TxError represents an error for a specific transaction.
type TxError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxError) Reset() {
	*x = TxError{}
	mi := &file_api_proto_hierachain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxError) ProtoMessage() {}

func (x *TxError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hierachain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxError.ProtoReflect.Descriptor instead.
func (*TxError) Descriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{3}
}

func (x *TxError) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TxError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TxError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// TxStatus represents the status of a transaction.
type TxStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Status        TxStatus_Status        `protobuf:"varint,2,opt,name=status,proto3,enum=hierachain.TxStatus_Status" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockHash     string                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatus) Reset() {
	*x = TxStatus{}
	mi := &file_api_proto_hierachain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatus) ProtoMessage() {}

func (x *TxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hierachain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatus.ProtoReflect.Descriptor instead.
func (*TxStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{4}
}

func (x *TxStatus) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TxStatus) GetStatus() TxStatus_Status {
	if x != nil {
		return x.Status
	}
	return TxStatus_PENDING
}

func (x *TxStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TxStatus) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

// Empty is an empty message for requests that don't need parameters.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_hierachain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hierachain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{5}
}

// HealthResponse contains the health status of the engine.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Stats         *EngineStats           `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_hierachain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hierachain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetStats() *EngineStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// EngineStats contains runtime statistics.
type EngineStats struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TransactionsProcessed int64                  `protobuf:"varint,1,opt,name=transactions_processed,json=transactionsProcessed,proto3" json:"transactions_processed,omitempty"`
	BlocksCreated         int64                  `protobuf:"varint,2,opt,name=blocks_created,json=blocksCreated,proto3" json:"blocks_created,omitempty"`
	PendingTransactions   int64                  `protobuf:"varint,3,opt,name=pending_transactions,json=pendingTransactions,proto3" json:"pending_transactions,omitempty"`
	AvgProcessingTimeMs   float64                `protobuf:"fixed64,4,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EngineStats) Reset() {
	*x = EngineStats{}
	mi := &file_api_proto_hierachain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineStats) ProtoMessage() {}

func (x *EngineStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hierachain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineStats.ProtoReflect.Descriptor instead.
func (*EngineStats) Descriptor() ([]byte, []int) {
	return file_api_proto_hierachain_proto_rawDescGZIP(), []int{7}
}

func (x *EngineStats) GetTransactionsProcessed() int64 {
	if x != nil {
		return x.TransactionsProcessed
	}
	return 0
}

func (x *EngineStats) GetBlocksCreated() int64 {
	if x != nil {
		return x.BlocksCreated
	}
	return 0
}

func (x *EngineStats) GetPendingTransactions() int64 {
	if x != nil {
		return x.PendingTransactions
	}
	return 0
}

func (x *EngineStats) GetAvgProcessingTimeMs() float64 {
	if x != nil {
		return x.AvgProcessingTimeMs
	}
	return 0
}

var File_api_proto_hierachain_proto protoreflect.FileDescriptor

const file_api_proto_hierachain_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/hierachain.proto\x12\n" +
	"hierachain\"\xbb\x02\n" +
	"\vTransaction\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12#\n" +
	"\rarrow_payload\x18\x04 \x01(\fR\farrowPayload\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x01R\ttimestamp\x12>\n" +
	"\adetails\x18\a \x03(\v2$.hierachain.Transaction.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x10TransactionBatch\x12;\n" +
	"\ftransactions\x18\x01 \x03(\v2\x17.hierachain.TransactionR\ftransactions\"\xc6\x01\n" +
	"\vBatchResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x10processed_tx_ids\x18\x03 \x03(\tR\x0eprocessedTxIds\x12,\n" +
	"\x12processing_time_ms\x18\x04 \x01(\x03R\x10processingTimeMs\x12+\n" +
	"\x06errors\x18\x05 \x03(\v2\x13.hierachain.TxErrorR\x06errors\"b\n" +
	"\aTxError\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\xc3\x01\n" +
	"\bTxStatus\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.hierachain.TxStatus.StatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\tR\tblockHash\"0\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\"\a\n" +
	"\x05Empty\"\x9a\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12-\n" +
	"\x05stats\x18\x04 \x01(\v2\x17.hierachain.EngineStatsR\x05stats\"\xd3\x01\n" +
	"\vEngineStats\x125\n" +
	"\x16transactions_processed\x18\x01 \x01(\x03R\x15transactionsProcessed\x12%\n" +
	"\x0eblocks_created\x18\x02 \x01(\x03R\rblocksCreated\x121\n" +
	"\x14pending_transactions\x18\x03 \x01(\x03R\x13pendingTransactions\x123\n" +
	"\x16avg_processing_time_ms\x18\x04 \x01(\x01R\x13avgProcessingTimeMs2\xdf\x01\n" +
	"\x10HieraChainEngine\x12D\n" +
	"\vSubmitBatch\x12\x1c.hierachain.TransactionBatch\x1a\x17.hierachain.BatchResult\x12G\n" +
	"\x12StreamTransactions\x12\x17.hierachain.Transaction\x1a\x14.hierachain.TxStatus(\x010\x01\x12<\n" +
	"\vHealthCheck\x12\x11.hierachain.Empty\x1a\x1a.hierachain.HealthResponseB4Z2github.com/VanDung-dev/HieraChain-Engine/api/protob\x06proto3"

var (
	file_api_proto_hierachain_proto_rawDescOnce sync.Once
	file_api_proto_hierachain_proto_rawDescData []byte
)

func file_api_proto_hierachain_proto_rawDescGZIP() []byte {
	file_api_proto_hierachain_proto_rawDescOnce.Do(func() {
		file_api_proto_hierachain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_hierachain_proto_rawDesc), len(file_api_proto_hierachain_proto_rawDesc)))
	})
	return file_api_proto_hierachain_proto_rawDescData
}

var file_api_proto_hierachain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_hierachain_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_hierachain_proto_goTypes = []any{
	(TxStatus_Status)(0),     // 0: hierachain.TxStatus.Status
	(*Transaction)(nil),      // 1: hierachain.Transaction
	(*TransactionBatch)(nil), // 2: hierachain.TransactionBatch
	(*BatchResult)(nil),      // 3: hierachain.BatchResult
	(*TxError)(nil),          // 4: hierachain.TxError
	(*TxStatus)(nil),         // 5: hierachain.TxStatus
	(*Empty)(nil),            // 6: hierachain.Empty
	(*HealthResponse)(nil),   // 7: hierachain.HealthResponse
	(*EngineStats)(nil),      // 8: hierachain.EngineStats
	nil,                      // 9: hierachain.Transaction.DetailsEntry
}
var file_api_proto_hierachain_proto_depIdxs = []int32{
	9, // 0: hierachain.Transaction.details:type_name -> hierachain.Transaction.DetailsEntry
	1, // 1: hierachain.TransactionBatch.transactions:type_name -> hierachain.Transaction
	4, // 2: hierachain.BatchResult.errors:type_name -> hierachain.TxError
	0, // 3: hierachain.TxStatus.status:type_name -> hierachain.TxStatus.Status
	8, // 4: hierachain.HealthResponse.stats:type_name -> hierachain.EngineStats
	2, // 5: hierachain.HieraChainEngine.SubmitBatch:input_type -> hierachain.TransactionBatch
	1, // 6: hierachain.HieraChainEngine.StreamTransactions:input_type -> hierachain.Transaction
	6, // 7: hierachain.HieraChainEngine.HealthCheck:input_type -> hierachain.Empty
	3, // 8: hierachain.HieraChainEngine.SubmitBatch:output_type -> hierachain.BatchResult
	5, // 9: hierachain.HieraChainEngine.StreamTransactions:output_type -> hierachain.TxStatus
	7, // 10: hierachain.HieraChainEngine.HealthCheck:output_type -> hierachain.HealthResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_hierachain_proto_init() }
func file_api_proto_hierachain_proto_init() {
	if File_api_proto_hierachain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_hierachain_proto_rawDesc), len(file_api_proto_hierachain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_hierachain_proto_goTypes,
		DependencyIndexes: file_api_proto_hierachain_proto_depIdxs,
		EnumInfos:         file_api_proto_hierachain_proto_enumTypes,
		MessageInfos:      file_api_proto_hierachain_proto_msgTypes,
	}.Build()
	File_api_proto_hierachain_proto = out.File
	file_api_proto_hierachain_proto_goTypes = nil
	file_api_proto_hierachain_proto_depIdxs = nil
}
