// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/hierachain.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HieraChainEngine_SubmitBatch_FullMethodName        = "/hierachain.HieraChainEngine/SubmitBatch"
	HieraChainEngine_StreamTransactions_FullMethodName = "/hierachain.HieraChainEngine/StreamTransactions"
	HieraChainEngine_HealthCheck_FullMethodName        = "/hierachain.HieraChainEngine/HealthCheck"
)

// HieraChainEngineClient is the client API for HieraChainEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HieraChainEngine is the main service for transaction processing.
type HieraChainEngineClient interface {
	// SubmitBatch submits a batch of transactions for processing.
	SubmitBatch(ctx context.Context, in *TransactionBatch, opts ...grpc.CallOption) (*BatchResult, error)
	// StreamTransactions streams transactions for high-throughput processing.
	StreamTransactions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Transaction, TxStatus], error)
	// HealthCheck returns the health status of the engine.
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type hieraChainEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewHieraChainEngineClient(cc grpc.ClientConnInterface) HieraChainEngineClient {
	return &hieraChainEngineClient{cc}
}

func (c *hieraChainEngineClient) SubmitBatch(ctx context.Context, in *TransactionBatch, opts ...grpc.CallOption) (*BatchResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResult)
	err := c.cc.Invoke(ctx, HieraChainEngine_SubmitBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hieraChainEngineClient) StreamTransactions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Transaction, TxStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HieraChainEngine_ServiceDesc.Streams[0], HieraChainEngine_StreamTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Transaction, TxStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HieraChainEngine_StreamTransactionsClient = grpc.BidiStreamingClient[Transaction, TxStatus]

func (c *hieraChainEngineClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, HieraChainEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HieraChainEngineServer is the server API for HieraChainEngine service.
// All implementations must embed UnimplementedHieraChainEngineServer
// for forward compatibility.
//
// HieraChainEngine is the main service for transaction processing.
type HieraChainEngineServer interface {
	// SubmitBatch submits a batch of transactions for processing.
	SubmitBatch(context.Context, *TransactionBatch) (*BatchResult, error)
	// StreamTransactions streams transactions for high-throughput processing.
	StreamTransactions(grpc.BidiStreamingServer[Transaction, TxStatus]) error
	// HealthCheck returns the health status of the engine.
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedHieraChainEngineServer()
}

// UnimplementedHieraChainEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHieraChainEngineServer struct{}

func (UnimplementedHieraChainEngineServer) SubmitBatch(context.Context, *TransactionBatch) (*BatchResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBatch not implemented")
}
func (UnimplementedHieraChainEngineServer) StreamTransactions(grpc.BidiStreamingServer[Transaction, TxStatus]) error {
	return status.Error(codes.Unimplemented, "method StreamTransactions not implemented")
}
func (UnimplementedHieraChainEngineServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedHieraChainEngineServer) mustEmbedUnimplementedHieraChainEngineServer() {}
func (UnimplementedHieraChainEngineServer) testEmbeddedByValue()                          {}

// UnsafeHieraChainEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HieraChainEngineServer will
// result in compilation errors.
type UnsafeHieraChainEngineServer interface {
	mustEmbedUnimplementedHieraChainEngineServer()
}

func RegisterHieraChainEngineServer(s grpc.ServiceRegistrar, srv HieraChainEngineServer) {
	// If the following call panics, it indicates UnimplementedHieraChainEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HieraChainEngine_ServiceDesc, srv)
}

func _HieraChainEngine_SubmitBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HieraChainEngineServer).SubmitBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HieraChainEngine_SubmitBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HieraChainEngineServer).SubmitBatch(ctx, req.(*TransactionBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _HieraChainEngine_StreamTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HieraChainEngineServer).StreamTransactions(&grpc.GenericServerStream[Transaction, TxStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HieraChainEngine_StreamTransactionsServer = grpc.BidiStreamingServer[Transaction, TxStatus]

func _HieraChainEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HieraChainEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HieraChainEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HieraChainEngineServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HieraChainEngine_ServiceDesc is the grpc.ServiceDesc for HieraChainEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HieraChainEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hierachain.HieraChainEngine",
	HandlerType: (*HieraChainEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBatch",
			Handler:    _HieraChainEngine_SubmitBatch_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _HieraChainEngine_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTransactions",
			Handler:       _HieraChainEngine_StreamTransactions_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/hierachain.proto",
}
